#ifndef ECVSCOMMUNICATION_GLOBAL_H
#define ECVSCOMMUNICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ECVSCOMMUNICATION_LIB
# define ECVSCOMMUNICATION_EXPORT Q_DECL_EXPORT
#else
# define ECVSCOMMUNICATION_EXPORT Q_DECL_IMPORT
#endif

#endif // ECVSCOMMUNICATION_GLOBAL_H
