#ifndef ECVSFILTER_GLOBAL_H
#define ECVSFILTER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef ECVSFILTER_LIB
# define ECVSFILTER_EXPORT Q_DECL_EXPORT
#else
# define ECVSFILTER_EXPORT Q_DECL_IMPORT
#endif

#endif // ECVSFILTER_GLOBAL_H
